(ns chose-your-own-adventure.voyage.data)

(def game {:start {:type :start
                   :title "Wake up"
                   :dialog (str "You're chased by an abominable creature."
                                " You tripped, felt and broke your right leg."
                                " You can't move and the creature approaches quickly."
                                " You lean on a rock to pull yourself on your feet but after looking up you realise"
                                " that the creature is right in front of you preparing to attack."
                                " (Do you close your eyes?)")
                   :transitions {"yes" :awake
                                 "no" :death-in-sleep}}
           :awake {:type :continue
                   :title "Breakfast ready"
                   :dialog (str "Your forehead is so wet that for a moment you thought you had fever"
                                " and that skipping school was a thing."
                                " You are so confused for what happened and the only thing you can focus"
                                " now is your mother yelling at you from downstairs that the breakfast is ready."
                                " (Do you eat breakfast?)")
                   :transitions {"yes" :travelling-to-school
                                 "no" :mum-initiative}}
           :death-in-sleep {:type :lose
                            :title "Game Over"
                            :dialog (str "Unfortunately something unexpected happened and you never woke up.")}
           :travelling-to-school {:type :continue
                                  :title "A Quiet Walk"
                                  :dialog (str "With all the energy provided by the avocado and a poached egg toast eaten for breakfast"
                                               " you feel a strange force running through your muscles."
                                               " (Do you start running?)")
                                  :transitions {"yes" :at-school
                                                "no" :car-accident}}
           :car-accident {:type :lose
                          :title "Game Over"
                          :dialog (str "Slowly crossing at the traffic lights."
                                       " A hasty driver not paying attention hits you violently ."
                                       " You end up under the wheels of the car."
                                       " There's nothing left to do, you're dead.")}
           :mum-initiative {:type :continue
                            :title "Mum Doing Mum's Things"
                            :dialog (str "Your mum after finding out that you're still in bed, she approaches you."
                                         " You feel her cold hand slipping on your face with an expression of compassion."
                                         " Maybe is the right time to ask her if you can stay at home."
                                         " (Do you ask her to stay at home?)")
                            :transitions {"yes" :lazy-boy
                                          "no" :in-the-car}}
           :lazy-boy {:type :lose
                      :title "Game Over"
                      :dialog (str "You are a shame."
                                   " You better stay at home while the rest of the world goes in search of adventure.")}
           :in-the-car {:type :skip
                        :title "A Quick Trip"
                        :dialog (str "As you sit beside the driver"
                                     " you think if that dream you had has any connection with reality."
                                     " The dream was strange and intense and you can only remember the crumbs and see blurred images."
                                     " The car wheel hits a bump and your mind returns to the present."
                                     " You look out the window, finally the car has arrived at school.")
                        :on-continue :at-school}
           :at-school {:type :win
                       :title "Maths Class"
                       :dialog (str "You just got to class late, while you entering the room you noticed everyone looks at you with curiosity."
                                    " The professor couldn't stop asking you why were you late."
                                    " You answer him skillfully in an elegant and evasive way."
                                    " After a big laugh from the public, you take a seat and read what was written on the board."
                                    " \"Each new term in the Fibonacci sequence is generated by adding the previous two terms."
                                    " By starting with 1 and 2, the first 10 terms will be:"
                                    " 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."
                                    " By considering the terms in the Fibonacci sequence whose values do not exceed four million,"
                                    " find the sum of the even-valued terms.\""
                                    " At this point you couldn't wait for the bell to ring."
                                    " (To be continued...)")}
           })
